# PyTorch

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/logo.png" width=150>

在这节课中，我们将学习PyTorch，它是一个用于构建动态神经网络的学习库。我们将在本课程中了解其基础知识，以及如何创建和使用张量（Tensor），而我们将在下一课中使用它制作模型。

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/pytorch.png" width=300>

# Tensor 基础知识

In [1]:
# 安装PyTorch库
!pip3 install torch

>  注意：上述安装PyTorch的方式与官网并不一致，因为这里是基于Colab云端安装的，而大家一般是使用pip或者conda来安装PyTorch。具体安装教程参考：https://pytorch.org/

In [2]:
import numpy as np
import torch

In [8]:
# 创建一个张量
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[ 0.0000e+00,  0.0000e+00,  3.0560e+00,  0.0000e+00],
        [ 6.5643e-01,  0.0000e+00, -1.9346e-27,  4.4395e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [9]:
# 创建一个随机张量
x = torch.randn(2, 3) # torch.randn对应于正态分布，而rand(2,3)对应于均匀分布
print (x)

tensor([[ 0.3339,  0.6490,  0.4074],
        [-0.6675,  0.7679, -0.7578]])


In [10]:
# 0和1张量
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
# 列表（List） → 张量
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
# NumPy 数组 → 张量
x = torch.from_numpy(np.random.rand(2, 3))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.6386, 0.2538, 0.3410],
        [0.0642, 0.4661, 0.4085]], dtype=torch.float64)


In [13]:
# 改变张量类型（张量默认为float类型）
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor 运算

In [14]:
# 加法
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[ 1.3580, -0.1676,  1.9344],
        [ 0.2936, -0.5372,  2.0063]])


In [15]:
# 向量点积
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[ 2.2155, -1.0355],
        [-2.7137,  1.2244]])


In [16]:
# 转置
x = torch.randn(2, 3)
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape))
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[ 2.0081,  1.9957, -0.2383],
        [-1.6856, -0.0176,  1.1884]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 2.0081, -1.6856],
        [ 1.9957, -0.0176],
        [-0.2383,  1.1884]])


In [17]:
# Reshape
z = x.view(3, 2)
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[ 2.0081,  1.9957],
        [-0.2383, -1.6856],
        [-0.0176,  1.1884]])


In [18]:
# reshaping的危险（意外后果）
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape))
print("Values: \n{}\n".format(x))
a = x.view(x.size(1), -1)
print("Size: {}".format(a.shape))
print("Values: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape))
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape))
print("Values: \n{}".format(c))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [19]:
# 维度操作
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # 为每列添加各行叠加的值
print("Values: \n{}".format(y))
z = torch.sum(x, dim=1) # 为每行添加各列叠加的值
print("Values: \n{}".format(z))

Values: 
tensor([[-0.7690, -1.3675,  1.5049],
        [ 0.1525,  1.5442,  1.1634]])
Values: 
tensor([-0.6165,  0.1766,  2.6683])
Values: 
tensor([-0.6316,  2.8601])


# 索引，切片和级联

In [20]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[ 0.7461, -1.5441,  0.4423, -0.5469],
        [ 0.4056,  0.5396,  0.2474, -1.9112],
        [ 0.0194,  1.2375,  1.0849,  0.7881]])
x[:1]: 
tensor([[ 0.7461, -1.5441,  0.4423, -0.5469]])
x[:1, 1:3]: 
tensor([[-1.5441,  0.4423]])


In [21]:
# 选择维度索引
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # 第0和第2列的值
print("Values: \n{}".format(chosen))
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # 来自（0,0）和（2,1）的值
print("Values: \n{}".format(chosen))

Values: 
tensor([[ 0.6241, -0.6282,  0.3452],
        [ 0.1629, -0.7626,  0.0362]])
Values: 
tensor([[0.6241, 0.3452],
        [0.1629, 0.0362]])
Values: 
tensor([0.6241, 0.0362])


In [22]:
# 级联
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # 按行堆叠（dim = 1按列堆叠）
print("Values: \n{}".format(y))

Values: 
tensor([[ 0.9618, -0.0135, -0.8225],
        [ 0.2649, -1.1035,  1.0892]])
Values: 
tensor([[ 0.9618, -0.0135, -0.8225],
        [ 0.2649, -1.1035,  1.0892],
        [ 0.9618, -0.0135, -0.8225],
        [ 0.2649, -1.1035,  1.0892]])


# 梯度

In [24]:
# 带有gradient bookkeeping的张量
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z是标量
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.9884, 0.1157, 0.8670, 0.2569],
        [0.5966, 0.2916, 0.5495, 0.0729],
        [0.0134, 0.3049, 0.9009, 0.3397]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


* $ y = 3x + 2 $
* $ z = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(z)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

# CUDA 张量

In [25]:
# CUDA可用吗？
print (torch.cuda.is_available())

True


如果上面的代码返回False，那么请转到菜单栏上的`Runtime`→`Change runtime type`并在`Hardware accelerator`下选择`GPU`。

In [33]:
# 创建一个CPU版的0张量
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [34]:
# 创建一个CUDA版的0张量
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor
